name: Test

on:
  workflow_dispatch:

jobs:
  slack-test:
    
    runs-on: ubuntu-latest
    env:
                 SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
                 SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
              
    steps:
      - uses: actions/checkout@v2
      
      - name: test slack file upload
        run: |
                 today=$(date +"%d_%m_%Y")                 
                 curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="BugBountyData-Nucli Scan Output File-$today" -F filename="nuclei-output_$today.txt" -F file=@nuclie-output.bak
